# Generated by Django 4.2 on 2025-11-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=60)),
                ('club', models.CharField(max_length=50, null=True)),
                ('position', models.CharField(choices=[('ATT', 'Attacker'), ('MID', 'Midfielder'), ('DEF', 'Defender'), ('GK', 'Goalkeeper')], max_length=3)),
                ('goals', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETIRED', 'Retired'), ('DECEASED', 'Deceased')], default='ACTIVE', max_length=10)),
                ('rating', models.IntegerField(default=50)),
            ],
        ),
    ]
